# Project Information
site_name: Material Perfection
site_url: https://krlite.github.io/Material-Perfection/
strict: false

# Contents
nav:
  - Landing: index.md

# Theme
theme:
  name: material
  custom_dir: overrides
  language: en
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/octagram
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/octagram-outline
        name: Switch to light mode
  # Tips: Relative paths can navigate to svgs under path 'mkdocs-material/material/.icons'
  icon:
    logo: logo
    repo: material/code-braces
  # Tips: currently, the text font is set under 'stylesheets/css/font.css'
  font:
    # text: 'Source Sans'
    code: 'JetBrains Mono'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    - toc.integrate

# Repository
repo_url: https://github.com/KrLite/Material-Perfection/
repo_name: KrLite/Material-Perfection
edit_uri: edit/main/docs/

# Copyright
copyright: 'Copyright &copy; 2023 KrLite'

# Customization
extra_javascript:
  - javascripts/mathjax.js # Markdown math resolver
  - javascripts/dark_mode.js # Auto dark mode
  - javascripts/parallax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css # Optimize general appearances
  - stylesheets/colors.css # Control global colors
  - stylesheets/font.css # Define the fonts
  - stylesheets/headings.css # Make the headings prettier
  - stylesheets/parallax.css

# Plugins
plugins:
  - search
  - mermaid2

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: ''
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
     smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
      auto_append:
        - includes/abbreviations.md
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
